<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Nvm.Material</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../Platform/Nvm.Contracts/Nvm.Contracts.csproj" />
    <ProjectReference Include="../../Platform/Nvm.Kernel/Nvm.Kernel.csproj" />
  </ItemGroup>
</Project>
