<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>Nvm.Host</RootNamespace>
    <AssemblyName>Nvm.Host.All</AssemblyName>
    <UserSecretsId>nvm-host-all</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="AspNetCore.HealthChecks.SqlServer" />
    <PackageReference Include="AspNetCore.HealthChecks.NpgSql" />
    <PackageReference Include="AspNetCore.HealthChecks.Uris" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../Platform/Nvm.Bus/Nvm.Bus.csproj" />
    <ProjectReference Include="../../Platform/Nvm.CommandStore/Nvm.CommandStore.csproj" />
    <ProjectReference Include="../../Platform/Nvm.Hosting/Nvm.Hosting.csproj" />
    <ProjectReference Include="../../Platform/Nvm.PublicObjectModel/Nvm.PublicObjectModel.csproj" />
    <ProjectReference Include="../../FunctionalBlocks/FactoryModel/Nvm.FactoryModel.csproj" />
  </ItemGroup>

</Project>
