<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Nvm.CommandStore</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <ProjectReference Include="../Nvm.Kernel/Nvm.Kernel.csproj" />
    <EmbeddedResource Include="Migrations/*.sql" />
  </ItemGroup>
</Project>
