<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Nvm.Quality.Hosting</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <ProjectReference Include="../Quality/Nvm.Quality.csproj" />
    <ProjectReference Include="../../Platform/Nvm.CommandStore/Nvm.CommandStore.csproj" />
    <ProjectReference Include="../../Platform/Nvm.EventStore/Nvm.EventStore.csproj" />
    <EmbeddedResource Include="Migrations/*.sql" />
  </ItemGroup>
</Project>
